name: Deploy Website To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Copy files to /temp/deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PVT_KEY }}
          source: "dist/*"
          target: "/var/www/html/"
          
      - name: Copy files to html
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PVT_KEY }}
          script: |
            sudo rm -rf assets /var/www/html/
            sudo rm -rf index.html /var/www/html/
            sudo rm -rf vite.svg /var/www/html/
            sudo cp -r /var/www/html/dist/* /var/www/html/

      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
